name: caribou
channels:
  - gpuci
  - rapidsai
  - nvidia
  - pytorch
  - conda-forge
dependencies:
  - ca-certificates
  - setuptools
  - wheel
  - biopython
  - h5py
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - tensorflow
  - keras
  - vaex-core
  - vaex-hdf5
  - vaex-ml
  - diskcache
