name: caribou
channels:
  - pytorch
  - conda-forge
dependencies:
  - setuptools
  - wheel
  - biopython
  - h5py
  - matplotlib
  - numpy
  - scikit-learn
  - scipy
  - tensorflow
  - keras
  - ray
  - modin[ray]
